spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ateixeira/react-frontend-test-app-argo-cd-app-of-apps
    targetRevision: main
  ingress:
    host: dev.example.com